import { useState, useEffect, useRef } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { onAuthStateChanged } from 'firebase/auth';
import { auth } from '../firebase';
import sessionManager from '../utils/sessionManager';
import DashboardGrid from '../components/dashboard/DashboardGrid';
import { HiSparkles } from 'react-icons/hi2';
import { FiArrowLeft, FiRefreshCw, FiUpload } from 'react-icons/fi';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8000';

const ModularDashboard = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const hasAutoGenerated = useRef(false);
  
  const [sessionId, setSessionId] = useState('');
  const [datasetId, setDatasetId] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState(null);
  
  const [components, setComponents] = useState([]);
  const [componentsData, setComponentsData] = useState({});

  // Auth check
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      if (!user) {
        navigate('/login');
      }
    });
    return () => unsubscribe();
  }, [navigate]);

  // Load session from location state or storage
  useEffect(() => {
    if (location.state?.sessionId) {
      setSessionId(location.state.sessionId);
    } else {
      // Try to load from localStorage
      const storedSessionId = localStorage.getItem('chatSessionId');
      if (storedSessionId) {
        setSessionId(storedSessionId);
      }
    }
    
    if (location.state?.datasetId) {
      setDatasetId(location.state.datasetId);
    } else {
      // Try to load from localStorage
      const storedDatasetId = localStorage.getItem('datasetId');
      if (storedDatasetId) {
        setDatasetId(storedDatasetId);
      }
    }
  }, [location]);

  // Auto-generate when sessionId is loaded and haven't generated yet
  useEffect(() => {
    if (sessionId && !hasAutoGenerated.current && components.length === 0) {
      hasAutoGenerated.current = true;
      handleGenerateDashboard();
    }
  }, [sessionId, components.length]);

  const handleGenerateDashboard = async () => {
    if (!sessionId) {
      setError('Please provide Session ID');
      return;
    }

    setIsGenerating(true);
    setError(null);

    try {
      // Step 1: Get component suggestions from Groq
      const payload = {
        session_id: sessionId,
        max_components: 6
      };
      
      // Only include dataset_id if it has a value
      if (datasetId) {
        payload.dataset_id = datasetId;
      }
      
      const suggestResponse = await fetch(`${API_BASE_URL}/dashboard/suggest-components`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      if (!suggestResponse.ok) {
        const errorData = await suggestResponse.json().catch(() => ({}));
        throw new Error(errorData.detail || `Server error: ${suggestResponse.status}`);
      }

      const suggestData = await suggestResponse.json();
      const suggestedComponents = suggestData.components || [];
      const actualDatasetId = suggestData.dataset_id;
      
      // Update dataset ID if it was auto-selected
      if (actualDatasetId && !datasetId) {
        setDatasetId(actualDatasetId);
      }
      
      setComponents(suggestedComponents);

      // Step 2: Fetch data for each component
      await fetchAllComponentsData(suggestedComponents, actualDatasetId);

    } catch (err) {
      console.error('Dashboard generation failed:', err);
      setError(err.message || 'Failed to generate dashboard');
    } finally {
      setIsGenerating(false);
    }
  };

  const fetchAllComponentsData = async (componentsList, useDatasetId) => {
    setIsLoading(true);
    const dataMap = {};
    const effectiveDatasetId = useDatasetId || datasetId;

    try {
      // Fetch data for all components in parallel
      const fetchPromises = componentsList.map(async (component) => {
        try {
          const response = await fetch(`${API_BASE_URL}/dashboard/component-data`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              session_id: sessionId,
              dataset_id: effectiveDatasetId,
              component: component
            })
          });

          if (response.ok) {
            const result = await response.json();
            return { componentId: component.id, data: result.data };
          }
          return null;
        } catch (error) {
          console.error(`Failed to fetch data for component ${component.id}:`, error);
          return null;
        }
      });

      const results = await Promise.all(fetchPromises);
      
      results.forEach((result) => {
        if (result) {
          dataMap[result.componentId] = result.data;
        }
      });

      setComponentsData(dataMap);
    } catch (err) {
      console.error('Failed to fetch components data:', err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleRefreshComponent = async (componentId) => {
    const component = components.find(c => c.id === componentId);
    if (!component) return;

    try {
      const response = await fetch(`${API_BASE_URL}/dashboard/component-data`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          session_id: sessionId,
          dataset_id: datasetId,
          component: component
        })
      });

      if (response.ok) {
        const result = await response.json();
        setComponentsData(prev => ({
          ...prev,
          [componentId]: result.data
        }));
      }
    } catch (error) {
      console.error(`Failed to refresh component ${componentId}:`, error);
    }
  };

  // Transform components with their data for display
  const dashboardBlocks = components.map(component => {
    const rawData = componentsData[component.id];
    
    // Transform data based on visualization type
    let transformedData = null;
    
    if (component.visualizationType === 'metric') {
      transformedData = transformMetricData(rawData, component);
    } else if (component.visualizationType === 'table') {
      transformedData = { rows: rawData || [] };
    } else if (component.visualizationType === 'chart' || component.visualizationType === 'pie') {
      transformedData = transformChartData(rawData, component);
    }

    return {
      ...component,
      data: transformedData,
      metadata: {
        lastUpdated: new Date().toISOString()
      }
    };
  });

  const transformMetricData = (data, component) => {
    if (!data || data.length === 0) return { metrics: [] };

    const firstRow = data[0];
    const metrics = [];

    // Extract metrics from the aggregation result
    Object.keys(firstRow).forEach(key => {
      if (key !== '_id') {
        metrics.push({
          label: key.replace(/_/g, ' ').toUpperCase(),
          value: firstRow[key]
        });
      }
    });

    return { metrics };
  };

  const transformChartData = (data, component) => {
    if (!data || data.length === 0) return null;

    const chartType = component.chartType || 'bar';
    
    // Build Plotly figure based on chart type
    if (chartType === 'line' || chartType === 'bar') {
      const xValues = data.map(row => row._id || row.category || row.x);
      const yValues = data.map(row => row.value || row.y || row.count);

      return {
        figure: {
          data: [{
            type: chartType,
            x: xValues,
            y: yValues,
            marker: { color: chartType === 'bar' ? '#818cf8' : undefined },
            line: chartType === 'line' ? { color: '#38bdf8' } : undefined
          }],
          layout: {
            margin: { t: 40, r: 20, b: 60, l: 60 }
          }
        }
      };
    } else if (chartType === 'pie') {
      const labels = data.map(row => row._id || row.category);
      const values = data.map(row => row.value || row.count);

      return {
        figure: {
          data: [{
            type: 'pie',
            labels: labels,
            values: values
          }],
          layout: {
            margin: { t: 40, r: 20, b: 40, l: 20 }
          }
        }
      };
    } else if (chartType === 'histogram') {
      const values = data.map(row => row.value || row.x);
      
      return {
        figure: {
          data: [{
            type: 'histogram',
            x: values,
            marker: { color: '#38bdf8' }
          }],
          layout: {
            margin: { t: 40, r: 20, b: 60, l: 60 }
          }
        }
      };
    }

    return null;
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
      {/* Header */}
      <div className="border-b border-slate-700/50 bg-slate-900/50 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <button
                onClick={() => navigate(-1)}
                className="p-2 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-slate-200 transition-colors"
              >
                <FiArrowLeft className="w-5 h-5" />
              </button>
              <div>
                <h1 className="text-2xl font-bold text-slate-100 flex items-center gap-2">
                  <HiSparkles className="w-6 h-6 text-indigo-400" />
                  Intelligent Dashboard
                </h1>
                <p className="text-slate-400 text-sm mt-1">
                  AI-powered modular visualizations
                </p>
              </div>
            </div>
            
            {components.length > 0 && (
              <button
                onClick={handleGenerateDashboard}
                disabled={isGenerating}
                className="flex items-center gap-2 px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-700 text-white transition-colors disabled:opacity-50"
              >
                <FiRefreshCw className={`w-4 h-4 ${isGenerating ? 'animate-spin' : ''}`} />
                Regenerate
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto">
        {/* Configuration Panel (if no components) */}
        {components.length === 0 && (
          <div className="p-6">
            <div className="bg-slate-800/30 border border-slate-700/50 rounded-lg p-6">
              <h2 className="text-lg font-semibold text-slate-200 mb-4">
                Generate Dashboard
              </h2>
              
              <div className="grid gap-4 mb-6">
                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-2">
                    Session ID
                  </label>
                  <input
                    type="text"
                    value={sessionId}
                    onChange={(e) => setSessionId(e.target.value)}
                    placeholder="Enter session ID"
                    className="w-full px-4 py-2 bg-slate-900/50 border border-slate-700 rounded-lg text-slate-200 placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-2">
                    Dataset ID
                  </label>
                  <input
                    type="text"
                    value={datasetId}
                    onChange={(e) => setDatasetId(e.target.value)}
                    placeholder="Enter dataset ID (optional)"
                    className="w-full px-4 py-2 bg-slate-900/50 border border-slate-700 rounded-lg text-slate-200 placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  />
                  <p className="text-slate-500 text-xs mt-1">
                    Leave empty to use the most recent dataset
                  </p>
                </div>
              </div>

              <button
                onClick={handleGenerateDashboard}
                disabled={isGenerating || !sessionId}
                className="w-full flex items-center justify-center gap-2 px-6 py-3 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isGenerating ? (
                  <>
                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                    Generating Dashboard...
                  </>
                ) : (
                  <>
                    <HiSparkles className="w-5 h-5" />
                    Generate Dashboard
                  </>
                )}
              </button>

              {error && (
                <div className="mt-4 p-4 bg-rose-500/10 border border-rose-500/50 rounded-lg text-rose-300 text-sm">
                  {error}
                </div>
              )}
            </div>
          </div>
        )}

        {/* Dashboard Grid */}
        <DashboardGrid
          blocks={dashboardBlocks}
          onRefreshBlock={handleRefreshComponent}
          isLoading={isLoading}
        />
      </div>
    </div>
  );
};

export default ModularDashboard;
